-- AlterTable
ALTER TABLE "rooms" ADD COLUMN     "floor" VARCHAR(50),
ADD COLUMN     "map_height" DOUBLE PRECISION DEFAULT 12,
ADD COLUMN     "map_width" DOUBLE PRECISION DEFAULT 15,
ADD COLUMN     "map_x" DOUBLE PRECISION,
ADD COLUMN     "map_y" DOUBLE PRECISION;
