const errorCodes = {
  // Auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Rooms
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_NAME_EXISTS: 'ROOM_NAME_EXISTS',
  ROOM_INACTIVE: 'ROOM_INACTIVE',

  // Bookings
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
  BOOKING_PAST_TIME: 'BOOKING_PAST_TIME',
  BOOKING_OUTSIDE_HOURS: 'BOOKING_OUTSIDE_HOURS',
  BOOKING_TOO_SHORT: 'BOOKING_TOO_SHORT',
  BOOKING_TOO_LONG: 'BOOKING_TOO_LONG',
  BOOKING_TOO_FAR_AHEAD: 'BOOKING_TOO_FAR_AHEAD',
  BOOKING_INVALID_STATUS: 'BOOKING_INVALID_STATUS',
  BOOKING_NOT_OWNER: 'BOOKING_NOT_OWNER',

  // Comments
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_EDIT_TIMEOUT: 'COMMENT_EDIT_TIMEOUT',

  // Templates
  TEMPLATE_LIMIT_REACHED: 'TEMPLATE_LIMIT_REACHED',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

module.exports = errorCodes;
